# Generated by Django 4.2.13 on 2024-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
